iczelia/bzip3

Makefile

I have `$CFLAGS` set in my environment already, so when I did `make`, it could not find `common.h`.
This tweak will conditionally set CFLAGS if not already set, and will always append `-Iinclude`. 
(My editor also cleaned up some trailing spaces on a couple of lines.)

Always append `-Iinclude` to CFLAGS

---

configure.ac

The final commit 42a066c added into #12 inverts the correct logic to be backwards. The real problem is that the detection of existing flags was being done after checking for CC and setting up library build options—which was setting some CFLAGS. This corrects the logic back to `test -n "$CFLAGS"` but moves the check earlier in the configure process so it happens before autotools starts setting any system specific CFLAGS on us.

Fix inverted CFLAGS detection, move earier in build

---

.github/workflows/release.yml
.gitignore
Makefile.am
bootstrap.sh
build-aux/git-version-gen
configure.ac

See #13 and #15
This automates two different parts of the release process:
1. Instead of hard coding a version in `configure.ac`, it derives the current version from either Git meta data (for clones) or from an included meta data file (for source packages). This means that the release process can now git `git tag X.Y.Z && git push --tags` (or of course adding a tag from the GitHub interface). Notably no changes need to be made *in* the source to get properly versioned releases.
This does have one drawback: building from Git clones is fine and building from source packages is fine, but building from `git archive` generated snapshot tar files is a wee bit harder. A hint is available in the `bootstrap.sh` file for how to make it work for anybody that hits that problem.
2. This builds the …

Add release automation stuff

---

Makefile.am
src/main.c

I added a `-v` flag to the binary that outputs the version as configured at build time. For tagged commits this should be the SEMVER bit only, for HEAD versions in between tags it should show some `git describe` output to pinpoint the current commit (including noting whether the tree was dirty or not at build time). This should help with bug reports from the wild as well as developers shuffiling multiple binaries around for testing.
I also added a `-h` flag to explicitly get the help output without returning an error status.

Add help and version flags, show version info in help

---

.gitignore
Makefile.am

This is to fix a logic bug in my own submissions. Handling setting the VERSION value in autoconf based on Git forces a reconfigure every time the current HEAD changes (by necessity). Tracking this but *also* allowing static source tarballs work nicely without any Git metadata involves an output file with a hard coded version generated at source package time. The project I copied this code from (one of my own, git-warp-time) did not have a BSD compatible target for this, so I rewrote it to work with `bmake` when submitting to this project. In doing that rewrite I overlooked and order of operations thing that is not causing the builds from source tarballs to trigger configure runs *twice*. It still works but wastes some cycles and makes autoconf look even more pedantically slow than it …

Fix version handling causing duplicate configure runs

---

.github/workflows/build.yml

This fixes an oversight on my part. Half way through #12 I realized `--(en|dis)able-pthread` was the wrong argument type and it should be `--with(|out)-pthread` instead. It can still be used as an on/off toggle, but if we ever need it this way we can use the with variant to get a path to the specific pthread headers to use rather than only autodetecting them. That last bit isn't setup I don't think, but this is at least the right kind of flag so we don't have to change it later.
I just forgot to fix the CI matrix after I changed it.

Fix CI build without pthread

---

.gitignore
Makefile.am

See #22. Merge then rebase the other CI work onto master to get the BSD fixups and all should be good.

Fixup rountrip test to play nice on `bmake`

---

src/main.c

In windows your program changes LF into CRLF which makes output archive unusable.
This fixes it.

set binary mode for standard in/output

---

Makefile.am
bzip3.pc.in
configure.ac

As mentioned in [comments here](https://github.com/kspalaiologos/bzip3/pull/12#issuecomment-1124826612).
**CAVEAT**: I haven't used this in anything myself! I am pretty confident in the autotools part of generating this template and installing in, but I'm not at all confident about the `Libs:` line in particular being correct for this project:
```
Libs: -L${libdir} -lbz3
```
It would be nice if somebody could confirm the result here is actually usable.

Generate and install pkg-config info so other projects can find headers easily

---

src/main.c

Name \`--version' option \`-V', not \`-v' as it's, traditionally, used as \`--verbose'. It's de facto standard for cmpressors.
I come across that trying to test verbosely (\`-t -v') and what I got was version string. That was unexpected and I had to check it twice. Do I made it to follow Dee facto standard  for other compressors.

Name version option -V

---

src/main.c

Make compression a default action.
To make it ~~look~~ behave like *nix compressor, make compression default action so it can be used like standard compressor:
./bzip3 \<file\>
It will be, in general, equivalent to
./bzip3 <file> [output-file]
Options work like usual.
It will also allow to be used with tar.

make compression default action

---

src/main.c

I was working on something else in this regard and noticed that help() and version() print to standard error.
Neither help nor version info are errors and according to GNU coding standards for [help](https://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html) and [version](https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html) it's recommend to print it on standard output, then exit successfully, and for version to put easily parseable version in first line, then brief copyright and licence information.
```
bzip3 1.1.4
Copyright...
License...
```
They should be printed to standard output for more prosaic reason - they can be paged through less/more, which helps to read it when it's long and search interesting information.
Also, technically, help had been slimmed down …

GNU standards for CLI for help(), version()

---

src/main.c

I made a mistake in licence in version() function of last [PR](https://github.com/kspalaiologos/bzip3/pull/42) while copying from [page](https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html). It should be LGPLv3, as it is now.
I couldn't go back as that branch was already deleted, therefore new PR. Hope it's the only and last mistake.

GNU standards for CLI; licence corrected

---

include/getopt-shim.h

hi,
the refs to the functions is:
1) https://github.com/kspalaiologos/bzip3/blob/master/include/getopt-shim.h#L52
2) https://github.com/kspalaiologos/bzip3/blob/master/include/getopt-shim.h#L54
according to the MSDN, on WIN32 we can use:
1) https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/lock-file
2) https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/unlock-file
tested on i686 & x86_64 Windows 7 using MinGW-W64 compiler.

flockfile/funlockfile for WIN32

---

Makefile.am
configure.ac

If a dynamic library is built (--enable-shared --disable-static-exe), the library object files were unnecessarily statically linked to the tool, duplicating the libbz3.c code among the tool and the library:
~~~~
$ ls -l bzip3 .libs/libbzip3.so.0.0.0
-rwxr-xr-x. 1 test test 171096 Oct 26 15:13 bzip3
-rwxr-xr-x. 1 test test 147408 Oct 26 15:13 .libs/libbzip3.so.0.0.0
~~~~
and the tool was not linked to the library at all:
~~~~
$ scanelf -n bzip3
TYPE   NEEDED FILE
ET_EXEC libc.so.6 bzip3
~~~~
The cause were an unconditional listing of libbz3.c among bzip3 tool sources, a typo in a bzip3_LDADD variable name, wrong evaluation of --disable-static-exe option, and an absence of ENABLE_STATIC aplication in Makefile.am.
This patch fixes all these issues on the assumption that an absence of …

Dynamically link a library to the tool if not disabled

---

Makefile.am

Debian Linux and Red Hat-derived distributions usually don't add `/usr/local/lib` to the library search path, and since #65 made the `bzip3` binary dependent on `libbz3.so`, on some stock configurations bzip3 might not work out of the box. This patch sets the `rpath` value to the libraries directory allowing us to sidestep this without forcing the user to set `LD_LIBRARY_PATH` manually.

Set rpath in the Makefile

---

src/main.c

Looks like some warnings got introduced in f25cc45a638e5bedcc58ebaeea59b0a1e526c98c
Before this patch:
```
make -j8
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
CC       src/libbz3.lo
CC       src/bzip3-main.o
src/main.c:375:71: warning: format specifies type 'long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
fprintf(stderr, "\t%ld -> %ld bytes, %.2f%%, %.2f bpb\n", bytes_read, bytes_written, (double)bytes_written * 100.0 / bytes_read, (double)bytes_written * 8.0 / bytes_read);
~~~                                    ^~~~~~~~~~
%llu
src/main.c:375:83: warning: format specifies type 'long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
fprintf(stderr, "\t%ld -> %ld bytes, %.2f%%, %.2f bpb\n", bytes_read, …
```

fix compiler warnings, %ld to %llu

---

src/main.c

Trying to copy \`setmode()' I realised that checking if `O_BINARY` is defined is redundant, not to mention it meant to be \`0x8000', although it works fine. It's defined since VC-6 and Mingw-3.4, so it can be used as \`O_BINARY'.
Sorry for the mess.

use mode defined in header

---

bz3cat
bz3grep
bz3less
bz3more
bz3most

The current shebangs on shell scripts use `#!/bin/sh` which is fine. `#!/usr/bin/env sh` uses the PATH environment variable to find an available `sh` shell, and uses the first one it finds. This can be nice for situations where the user has installed a version of `sh` that they prefer in `/usr/local` or something.

Use `/usr/bin/env sh` for shebangs

---

src/main.c

All standard and even non standard compressors accept option to keep (not delete) files as they delete files by default. Here you don't delete original file but accepting it will help with unifying scripts that use it.
Even compressors that don't delete by default accept this option for compatibility.

accept option -k: keep (don't delete) input files

---

Makefile.am

`make roundtrip` fails on `srcdir != builddir`
```
$ cd bzip3
$ ./bootstrap.sh
$ mkdir build
$ cd build
$ ../configure
$ make roundtrip
rm -f LICENSE2
./bzip3 -v -feb 6 LICENSE
Error: failed to open input file `LICENSE': No such file or directory
```

Fix `make roundtrip` on `srcdir != builddir`

---

Makefile.am

Build on cygwin
```
$ uname -mrs
CYGWIN_NT-10.0-19045 3.4.3-1.x86_64 x86_64
$ cd bzip3
$ ./bootstrap.sh
$ ./configure --enable-shared --disable-static CC=gcc
$ make V=1
make  all-am
make[1]: Entering directory '/cygdrive/e/bzip3'
/bin/sh ./libtool  --tag=CC   --mode=link gcc -I./include -g -O2 -pthread -DPTHREAD -O2 -g3 -fPIC -march=native -mtune=native -version-info 0:0:0  -o libbzip3.la -rpath /usr/local/lib src/libbz3.lo  -lpthread
libtool:   error: can't build x86_64-pc-cygwin shared library unless -no-undefined is specified
make[1]: *** [Makefile:575: libbzip3.la] Error 1
make[1]: Leaving directory '/cygdrive/e/bzip3'
make: *** [Makefile:433: all] Error 2
```

Build on cygwin

---

src/main.c

https://github.com/kspalaiologos/bzip3/blob/5dc0802d64b5b5702997eff6b228623fedfb0204/src/main.c#L656
https://github.com/kspalaiologos/bzip3/blob/5dc0802d64b5b5702997eff6b228623fedfb0204/src/main.c#L672
`malloc` here allocates some space on the heap but doesn't free it after being used. 
Compiling with GCC (address sanitization enabled) detected this issue.
```
Direct leak of 12 byte(s) in 1 object(s) allocated from:
#0 0x7f03ae4beedf in __interceptor_malloc (/usr/lib/libasan.so.8+0xbeedf)
#1 0x55da54e41ed7 in main src/main.c:656
SUMMARY: AddressSanitizer: 12 byte(s) leaked in 1 allocation(s).
```

Fix: free output after being used

---

src/main.c

Closes #90
This is a naive approach to getting a working build again from the *master* branch. I don't understand completely what #89 was supposed to fix, but whatever it was supposed to do it broke everything else. This simply reverts the change. A better fix may be possible, either to configure in a way that the code works or to solve the same original problem in a better way, but pending such a thing being proposed I suggest the default HEAD version working and passing tests.

Revert PR #89

---

src/libbz3.c

This patch set resolves compiler warnings about discarding const qualifiers.

Const warnings

---

.github/workflows/build.yml
CMakeLists.txt

This is initial support, so this is not as mature as the existing build system with Autotools.
This is intended to add CMake support to BZip3, and not to replace the existing build system.

Initial CMake support

---

CMakeLists.txt

Compilation fails on various platforms without -pthread and this is consistent behaviour with GNU Autotools build

CMake: Explicitly link with pthreads

---

CMakeLists.txt

For consistency with GNU Autotools build disable -march=native by default

CMake: Disable -march=native by default

---

bzip3.1.in
src/libbz3.c
src/main.c

This is an option to remove input files after successful compression or decompression. This is silently ignored if output is stdout.
Also, I am running `clang-format` with this change and before it.
Closes #122

Add `--rm` option

---

examples/fuzz.c

This is a small patch around the fuzzer example.
Makes it more friendly for non-C devs.
Changes are pretty small:
- Explicitly specifies current directory (previously it required you to change it, for `afl-clang`, without indication).
- The command to build with UndefinedBehaviour/AddressSanitizer was changed to `clang` from `gcc`, to match `afl-clang` usage above. [unless the difference was deliberate, then please undo in commit]
- Replaced removed `compress-test` mention with an instruction to run binary.
Since the `compress-test` example no longer exists (it was removed, as it served as a bad example of how to use C, according to commit message); I updated the docs to instead direct the user to build the main binary to use for compressing the input.
I also added some free(s) to the …

Improved: Make fuzzing setup guide a tiny bit clearer.

---

README.md

I found this made comparison easier, and highlighted the higher compression ration achieved by bzip3.

README: Tabulate results

---

bzip3.pc.in

The pkg-config file has License variable that allows you to set the license for the software. 
This sets LGPL-3.0-or-later to License.
Ref: https://github.com/pkgconf/pkgconf/blob/master/man/pc.5#L116

Add License variable to pkg-config file

---

CMakeLists.txt

Attempting to build with pthreads turned on on Windows triggers a build failure due to missing pthreads headers. As Windows isn't a pthreads platform, it seems like this should be off by default.

CMake: Disable pthreads by default on Windows & !MinGW.

---

CMakeLists.txt

If CMAKE_CURRENT_SOURCE_DIR is not specified to ${BZIP3_MAN}.in, it will refer to the current directory, which will result in an error if user builds with out-of-source builds.
This sets CMAKE_CURRENT_SOURCE_DIR and supports out-of-source builds.
```
$ mkdir t && cd t && cmake ..
-- The C compiler identification is GNU 14.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
CMake Error: File /home/iwamatsu/dev/bzip3/bz3grep.1 does not exist.
CMake Error at CMakeLists.txt:152 (configure_file):
configure_file Problem …
```

cmake: Set CMAKE_CURRENT_SOURCE_DIR to path of ${BZIP3_MAN}.in
